---
- name: PN-CLI Cluster delete
  hosts: spine[0]
  user: pluribus

  tasks: 
  - name: Delete cluster
    pn_cluster: pn_cliusername=admin pn_clipassword=admin pn_command=cluster-delete pn_name=spinecluster 
    register: cmd_output
  - debug: var=cmd_output
