--- 
- hosts: spine[0]
  name: "PN-CLI Fabric Show Test"
  user: pluribus
  
  tasks: 
    - name: "Test Fabric Show CLI command"
      pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=fabric-node-show
      register: cmd_output
    - debug: var=cmd_output  
  


    
