--- 
- hosts: spine[0]
  name: "PN-CLI trunk Show Test"
  user: pluribus

  tasks: 
    - name: "Test trunk Show CLI command"
      pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=trunk-show
      register: cmd_output
    - debug: var=cmd_output  

