--- 
- hosts: spine[0]
  name: "PN-CLI trunk Show Test"
  user: pluribus

  tasks: 
    - name: "Test trunk Show CLI command"
      pn_show: pn_cliusername=network-admin pn_clipassword=test123 pn_command=trunk-show pn_quiet=True
      register: cmd_output
    - debug: var=cmd_output  

