---
- name: PN-CLI trunk Delete
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Delete trunk 
    pn_trunk: pn_cliusername=admin pn_clipassword=admin pn_command=trunk-delete pn_name=spine1-to-leaf
    register: cmd_output
  - debug: var=cmd_output
