---
- name: PN-CLI trunk Create
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Create trunk 
    pn_trunk: pn_cliusername=admin pn_clipassword=admin pn_command=trunk-create pn_name=spine1-to-leaf pn_ports=11,12,13,14
    register: cmd_output
  - debug: var=cmd_output
