---
- name: PN-CLI vrouter-interface show command
  hosts: spine[0]
  user: pluribus

  tasks:
  - name: Test CLI vrouter-interface-show command
    pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=vrouter-interface-show
    register: cmd_output
  - debug: var=cmd_output
