---
- name: PN-CLI Test
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Test VLAN Stats Settings Show CLI commands 
    pn_show: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-stats-settings-show pn_quiet=True 
    register: cmd_output
  - debug: var=cmd_output 
    
