---
- name: PN-CLI Test
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Test VLAN Stats Settings Show CLI commands 
    pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=vlan-stats-settings-show
    register: cmd_output
  - debug: var=cmd_output 
    
