---
- name: PN-CLI VLAG Create
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Create VLAG 
    pn_vlag: pn_cliusername=admin pn_clipassword=admin pn_command=vlag-create pn_name=spine-to-leaf pn_port=spine1-to-leaf pn_peer_port=spine2-to-leaf pn_mode=active-active pn_peer_switch=onvlspine2
    register: cmd_output
  - debug: var=cmd_output 
