---
- name: PN-CLI vrouter bgp add
  hosts: spine[0]
  user: pluribus  

  tasks:
  - name: Add vrouter bgp 
    pn_vrouterbgp: pn_cliusername=admin pn_clipassword=admin pn_command=vrouter-bgp-add pn_vrouter_name=ansible-vrouter pn_neighbor=104.104.104.2 pn_remote_as=65000
    register: cmd_output
  - debug: var=cmd_output 
