---
- name: PN-CLI VLAN Delete
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Delete VLAN 
    pn_vlan: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-delete pn_vlanid=300 pn_quiet=True
    register: cmd_output
  - debug: var=cmd_output 
