---
- name: PN-CLI VLAG Delete
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Delete VLAG 
    pn_vlag: pn_cliusername=admin pn_clipassword=admin pn_command=vlag-delete pn_name=spine-to-leaf
    register: cmd_output
  - debug: var=cmd_output 
