---
- name: PN-CLI VLAG Delete
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Delete VLAG 
    pn_vlag: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlag-delete pn_name=spine-to-leaf pn_quiet=True
    register: cmd_output
  - debug: var=cmd_output 
