---
- name: PN-CLI vrouter show command
  hosts: spine[0]
  user: pluribus

  tasks:
  - name: Test CLI vrouter-show command
    pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=vrouter-show
    register: cmd_output
  - debug: var=cmd_output
