---
- name: PN-CLI VLAN Create
  hosts: spine[0]
  user: root

  tasks:
  - name: Create VLAN 
    pn_vlan: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-create pn_vlanid=303 pn_scope=fabric pn_quiet=True
    register: cmd_output
  - debug: var=cmd_output 
