---
- name: PN-CLI vrouter Delete
  hosts: spine[0]
  user: pluribus  

  tasks:
  - name: Delete vrouter 
    pn_vrouter: pn_cliusername=admin pn_clipassword=admin pn_command=vrouter-delete  pn_name=ansible-vrouter
    register: cmd_output
  - debug: var=cmd_output 
