---
- name: PN-CLI VLAN Create
  hosts: spine[0]
  user: pluribus

  tasks:
  - name: Create VLAN 
    pn_vlan: pn_cliusername=admin pn_clipassword=admin pn_command=vlan-create pn_vlanid=303 pn_scope=fabric
    register: cmd_output
  - debug: var=cmd_output 
