--- 
- hosts: spine[0]
  name: "PN-CLI VLAN Show Test"
  user: pluribus

  tasks: 
    - name: "Test VLAN Show CLI command"
      pn_show: pn_cliusername=admin pn_clipassword=admin pn_command=vlan-show
      register: cmd_output
    - debug: var=cmd_output  
  


    
