---
- name: PN-CLI VLAN Delete
  hosts: spine[0]
  user: pluribus
  

  tasks:
  - name: Delete VLAN 
    pn_vlan: pn_cliusername=admin pn_clipassword=admin pn_command=vlan-delete pn_vlanid=300 
    register: cmd_output
  - debug: var=cmd_output 
