---
#L3 ZTP

pn_net_address: '172.168.1.0'         # optional, , Specify network address required to calculate link IPs for layer3 fabric, Network Address, text
pn_cidr: '24'                         # optional, , Specify subnet mask required to calculate link IPs for layer3 fabric, Subnet Mask, text
pn_supernet: '30'                     # optional, , Specify supernet mask required to calculate link IPs for layer3 fabric, Supernet, text
pn_assign_loopback: True              # optional, True:False, Flag to indicate if loopback ips should be assigned to vrouters, Assign Loopback IPs, boolean
pn_loopback_ip: '109.109.109.0/24'    # optional, 109.109.109.0/24, Loopback IP to be assigned to vrouters, Loopback IP, text
pn_bfd: True                          # optional, True:False, Flag to indicate if BFD config should be added to vrouter interfaces, Add BFD, boolean
pn_bfd_min_rx: 200                    # optional, , Specify BFD-MIN-RX value required for adding BFD configuration to vrouter interfaces, BFD MIN RX, text
pn_bfd_multiplier: 3                  # optional, , Specify BFD_MULTIPLIER value required for adding BFD configuration to vrouter interfaces, BFD MULTIPLIER, text
pn_update_fabric_to_inband: False     # optional, True:False, Flag to update fabric network to in-band, Update Fabric Network, boolean
pn_stp: True                          # optional, True:False, Flag to enable STP at the end of configuration, STP, boolean
