---

### Variables for L3 ZTP setup. ###

# These are optional variables since default values exists for them.
pn_net_address: '172.168.1.0'         # Network address required to calculate link IPs for layer3 fabric.
pn_cidr: '24'                         # Subnet mask required to calculate link IPs for layer3 fabric.
pn_supernet: '30'                     # Supernet mask required to calculate link IPs for layer3 fabric.
pn_assign_loopback: True              # Flag to indicate if loopback ips should be assigned to vrouters. Default: False.
pn_loopback_ip: '109.109.109.0/24'    # Loopback ip value for vrouters. Default: 109.109.109.0/24.
pn_bfd: True                          # Flag to indicate if BFD config should be added to vrouter interfaces. Default: False.
pn_bfd_min_rx: 200                    # BFD-MIN-RX value required for adding BFD configuration to vrouter interfaces.
pn_bfd_multiplier: 3                  # BFD_MULTIPLIER value required for adding BFD configuration to vrouter interfaces.
pn_update_fabric_to_inband: False     # Flag to indicate if fabric network should be updated to in-band. Default: False.
pn_stp: True                          # Flag to enable STP. Default: True.

