---

### Variables for eBGP/OSPF configuration. ###

# These are optional since default value exists for them.
pn_bfd: True                          # Flag to indicate if BFD config should be added to eBGP/ospf. Default: False.
pn_routing_protocol: 'ebgp'           # Routing protocol to configure. Choices are ['ebgp', 'ospf']
pn_bgp_maxpath: '16'                  # BGP-MAXPATH value to be assigned to vrouters. Default: 16
pn_bgp_redistribute: 'connected'      # BGP-REDISTRIBUTE value to be assigned to vrouters. Chocies: none, static, connected, rip, ospf. Default: connected
pn_bgp_as_range: '65000'              # BGP-AS-RANGE value to be assigned to vrouters. Default: 65000
pn_ibgp_ip_range: '75.75.75.0/30'     # iBGP IP range to be assigned to interfaces. Default: '75.75.75.0/30'
pn_ibgp_vlan: '4040'                  # iBGP vlan value to be assigned to interfaces. Default 4040
pn_ospf_area_id: '0'                  # Area id to configure for ospf. Default: 0

