---

### Variables for L3 ZTP setup. ###

# These are optional variables since default values exists for them.
pn_net_address: '172.168.1.0'         # Network address required to calculate link IPs for layer3 fabric.
pn_cidr: '24'                         # Subnet mask required to calculate link IPs for layer3 fabric.
pn_supernet: '30'                     # Supernet mask required to calculate link IPs for layer3 fabric.
pn_assign_loopback: True              # Flag to indicate if loopback ips should be assigned to vrouters. Default: False.
pn_loopback_ip: '109.109.109.0/24'    # Loopback ip value for vrouters. Default: 109.109.109.0/24.
pn_bfd: True                          # Flag to indicate if BFD config should be added to vrouter interfaces. Default: False.
pn_bfd_min_rx: 200                    # BFD-MIN-RX value required for adding BFD configuration to vrouter interfaces.
pn_bfd_multiplier: 3                  # BFD_MULTIPLIER value required for adding BFD configuration to vrouter interfaces.
pn_update_fabric_to_inband: False     # Flag to indicate if fabric network should be updated to in-band. Default: False.
pn_stp: True                          # Flag to enable STP. Default: True.


### Variables for L3 VRRP setup. ###

# These are mandatory variables since default values exists for them.
csv_file: vrrp_l3.csv  # VRRP Layer3 data csv file.


### Variables for eBGP/OSPF configuration. ###

# These are optional since default value exists for them.
pn_routing_protocol: 'ebgp'           # Routing protocol to configure. Choices are ['ebgp', 'ospf']
pn_bgp_maxpath: '16'                  # BGP-MAXPATH value to be assigned to vrouters. Default: 16
pn_bgp_redistribute: 'connected'      # BGP-REDISTRIBUTE value to be assigned to vrouters. Chocies: none, static, connected, rip, ospf. Default: connected
pn_bgp_as_range: '65000'              # BGP-AS-RANGE value to be assigned to vrouters. Default: 65000
pn_ibgp_ip_range: '75.75.75.0/30'     # iBGP IP range to be assigned to interfaces. Default: '75.75.75.0/30'
pn_ibgp_vlan: '4040'                  # iBGP vlan value to be assigned to interfaces. Default 4040
pn_ospf_area_id: '0'                  # Area id to configure for ospf. Default: 0
