---
- name: Add vrouter bgp 
  pn_vrouterbgp: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-bgp-add pn_vrouter_name=ansible-vrouter pn_neighbor=104.104.104.2 pn_remote_as=201 pn_quiet=True
  register: cmd_output
- debug: var=cmd_output 
