---


- name: Reset switches
  hosts: localhost

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Switch config reset
      pn_switch_config_reset:
        pn_cliusername: "{{ USERNAME }}"           # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"           # Cli password (value comes from cli_vault.yml).
        pn_host_list: "{{ groups['{{ reset_mode }}'] }}"        # List of all switches
        pn_host_ips: "{{ groups['{{ reset_mode }}'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"  # IPs of all switches separated by comma
      register: reset_out                          # Variable to hold/register output of the above tasks.

    - name: Wait for nvOSd to reboot
      pause:
        minutes: 2
      when: reset_out.changed
