#L3 VRRP eBGP
---


- name: Configure L3 VRRP with eBGP
  hosts: spine[0]
  become: true
  # become_method: su
  # become_user: root

  vars_files:
  - cli_vault.yml

  tasks:
    # This task is to configure VRRP for Layer 3 fabric.
    # It takes required VRRP config data from csv file.
    # It uses pn_l3_vrrp.py module from library/ directory.
    # pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
    - name: Configure L3 vrrp
      pn_l3_vrrp:
        pn_cliusername: "{{ USERNAME }}"        # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"        # Cli password (value comes from cli_vault.yml).
        pn_spine_list: "{{ groups['spine'] }}"  # List of all spine switches mentioned under [spine] grp in hosts file.
        pn_leaf_list: "{{ groups['leaf'] }}"    # List of all leaf switches mentioned under [leaf] grp in hosts file.
        pn_csv_data: "{{ lookup('file', '{{ csv_file }}') }}"  # Csv file containing L3 vrrp data.
      register: vrrp_out                        # Variable to hold/register output of the above tasks.
      until:  vrrp_out.failed != true           # If error pops up it will retry the code
      retries: 3                                # This is the retries count
      delay: 1
      # ignore_errors: yes                      # Flag to indicate if we should ignore errors if any.

    - pause:
        seconds: 2                              # Pause playbook execution for specified amount of time.


    # This task is to configure ZTP for layer3 fabric.
    # It uses pn_l3_ztp.py module from library/ directory.
    # pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
    # If the tasks fails then it will retry as specified by retries count.
    - name: Auto configure link IPs
      pn_l3_ztp:
        pn_cliusername: "{{ USERNAME }}"                # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"                # Cli password (value comes from cli_vault.yml).
        pn_spine_list: "{{ groups['spine'] }}"          # List of all spine switches mentioned under [spine] grp in hosts file.
        pn_leaf_list: "{{ groups['leaf'] }}"            # List of all leaf switches mentioned under [leaf] grp in hosts file.
        pn_net_address: "{{ pn_net_address }}"          # Network address required to calculate link IPs for layer3 fabric.
        pn_cidr: "{{ pn_cidr }}"                        # Subnet mask required to calculate link IPs for layer3 fabric.
        pn_supernet: "{{ pn_supernet }}"                # Supernet mask required to calculate link IPs for layer3 fabric.
        pn_loopback_ip: "{{ pn_loopback_ip }}"          # Loopback ip starting value for vrouters. Default: 109.109.109.0/24.
        pn_bfd: "{{ pn_bfd }}"                          # Flag to indicate if BFD config should be added to vrouter interfaces. Default: False.
        pn_bfd_min_rx: "{{ pn_bfd_min_rx }}"            # BFD-MIN-RX value required for adding BFD configuration to vrouter interfaces.
        pn_bfd_multiplier: "{{ pn_bfd_multiplier }}"    # BFD_MULTIPLIER value required for adding BFD configuration to vrouter interfaces.
        pn_update_fabric_to_inband: "{{ pn_update_fabric_to_inband }}"  # Flag to indicate if fabric network should be updated to in-band. Default: False.
        pn_stp: "{{ pn_stp }}"                          # Flag to enable STP (spanning tree protocol). Default: False.
      register: ztp_l3_out                              # Variable to hold/register output of the above tasks.
      until:  ztp_l3_out.failed != true                 # If error pops up it will retry the code
      retries: 3                                        # This is the retries count
      delay: 1
      # ignore_errors: yes                              # Flag to indicate if we should ignore errors if any.

    - pause:
        seconds: 2                                      # Pause playbook execution for specified amount of time.

    # This task is to configure eBGP.
    # It uses pn_ebgp_ospf.py module from library/ directory.
    # pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
    - name: Configure eBGP
      pn_ebgp_ospf:
        pn_cliusername: "{{ USERNAME }}"                   # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"                   # Cli password (value comes from cli_vault.yml).
        pn_spine_list: "{{ groups['spine'] }}"             # List of all spine switches mentioned under [spine] grp in hosts file.
        pn_leaf_list: "{{ groups['leaf'] }}"               # List of all leaf switches mentioned under [leaf] grp in hosts file.
        pn_bfd: "{{ pn_bfd }}"                             # Indicate if BFD config should be added to eBGP. Default: False.
        pn_routing_protocol: 'ebgp'                        # Routing protocol to configure. Choices are ['ebgp', 'ospf']
        pn_bgp_maxpath: "{{ pn_bgp_maxpath }}"             # BGP-MAXPATH value to be assigned to vrouters. Default: 16
        pn_bgp_redistribute: "{{ pn_bgp_redistribute }}"   # BGP-REDISTRIBUTE value to be assigned to vrouters. Choices are [none, static, connected, rip, ospf]. Default: connected
        pn_bgp_as_range: "{{ pn_bgp_as_range }}"           # BGP-AS-RANGE value to be assigned to vrouters. Default: 65000
        pn_ibgp_ip_range: "{{ pn_ibgp_ip_range }}"         # iBGP IP range to be assigned to vrouter interfaces. Default: '75.75.75.0/24'
        pn_ibgp_vlan: "{{ pn_ibgp_vlan }}"                 # iBGP vlan value to be assigned to vrouter interfaces. Default 4040
      register: bgp_out                                    # Variable to hold/register output of the above tasks.
      until: bgp_out.failed != true                        # If the above code fails it will retry the code
      retries: 3                                           # This is the retries count
      delay: 1
      # ignore_errors: yes                                 # Flag to indicate if we should ignore errors if any.

    - pause:
        seconds: 2                                         # Pause playbook execution for specified amount of time.
