---

- name: Configure eBGP
  hosts: switch[0]

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Create vrouter
      pn_vrouter_creation:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_loopback_ip: "{{ pn_loopback_ip }}"
        pn_switch_list: "{{ groups['switch'] }}"

    - name: Configure eBGP
      pn_ebgp_configuration:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_bgp_data: "{{ lookup('file', '{{ bgp_csv_file }}') }}"
        pn_switch_list: "{{ groups['switch'] }}" 
