# PLAYBOOK TO ENABLE ROOT SSH LOGIN

# The playbook does the following tasks:
#   Disable the empty password login
#   Enable the root login
#   Resatart the ssh daemon
#   Change/update the root-user password

# ---- VARIABLES ----
# The 2 local variables used are:
#   sshd_config : This variable stores the path of the sshd_config file
#   sshd: This variable stores the name of the ssh daemon process

# ---- VARS_FILES ----
# The vars_files contain the path of the ansible-vault file which contains the password for the root-user
# The name of the ansible vault file is cli_vault.yml in the case below
# The password can be retrieved using the variable name 'PASSWORD' from the vault file
# NOTE: WHILE USING DIFFERENT ROOT-USER PASSWORD(OTHER THAN DEFAULT),
#       assign the password to a new variable ROOT_PASSWORD in the vault file
#       and replace {{ PASSWORD | password_hash('sha512') }} with
#       {{ ROOT_PASSWORD | password_hash('sha512') }} in this playbook in the last task below

# ---- COMMAND ----
# This playbook can be run using following command:
#   ansible-playbook -i <hosts_file> <playbook_name> [--ask-pass] [--ask-vault-pass] [-u username] [-K]
#   eg: ansible-playbook -i hosts pn_enable_root_ssh.yml --ask-pass --ask-vault-pass -u pluribus -K

# --- HOSTS FILE ----
# The content of the hosts file is as follow:
#   <switch_name> <ansible_hosts=switch_ip_address>
#   eg: ansible-spine1 ansible_hosts=10.10.10.10
# NOTE: Hosts file can contain any number of the hosts

# ---- STEPS TO DO BEFORE RUNNING THE PLAYBOOK ----
# 1) make a hosts file and insert all the hosts-name and hosts-ip as shown above
# 2) assign path of ssh_config file to sshd_config local variable below
# 3) assign the ssh daemon name to sshd local variable below
# 4) run the command from above using the path of the hosts file from point 1
# NOTE: Do the needed for the root-password as directed in the VARS_FILES section above

---


- hosts: all
  become: yes

  vars_files:
  - cli_vault.yml

  vars:
  - sshd_config: /etc/ssh/sshd_config
  - sshd: ssh

  tasks:
  - name: Disable empty password login
    lineinfile: dest={{ sshd_config }} regexp="^#?PermitEmptyPasswords" line="PermitEmptyPasswords no"
  
  - name: Enable remote root login
    lineinfile: dest={{ sshd_config }} regexp="^#?PermitRootLogin" line="PermitRootLogin yes"

  - name: Restart ssh daemon
    service: name={{ sshd }} state=restarted

  - name: Change root password
    user: name=root update_password=always password={{ PASSWORD | password_hash('sha512') }}
