---

# This task is to configure eBGP.
# It uses pn_ebgp.py module from library/ directory.
# pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
# If you don't specify values for pn_bgp_maxpath, pn_bgp_redistribute, pn_bgp_as_range,
# then it will take the default values specified in the pn_ebgp.py module.
# If the tasks fails then it will retry as specified by retries count.
- name: Zero Touch Provisioning - BGP setup
  hosts: spine[0]
  serial: 1
  become: true
  become_method: su
  become_user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Configure eBGP
      pn_ebgp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_spine_list: "{{ groups['spine'] }}"
        pn_leaf_list: "{{ groups['leaf'] }}"
        # pn_bgp_maxpath:                       # default 16
        # pn_bgp_redistribute:                  # default connected
        # pn_bgp_as_range:                      # default 65000
      register: bgp_out
      until: bgp_out.failed != true             # If the above code fails it will retry the code
      retries: 3                                # This is the retries count
      delay: 1
      ignore_errors: yes

    - debug:
        var: bgp_out.stdout_lines

    - pause:
        seconds: 2
