---


- name: Zero Touch Provisioning - Initial setup
  hosts: all
  serial: 1
  become: true
  user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Auto accept EULA, Disable STP, enable ports and create/join fabric
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        # pn_fabric_retry: 1
        pn_fabric_name: 'ztp-fabric'
        pn_run_l2_l3: False
      register: ztp_out
      until: ztp_out.failed != true  # if the above code fails it will retry the code
      retries: 3                     # ztp_out.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 1
      ignore_errors: yes

    - debug: var=ztp_out
    - pause: seconds=2
