---


- name: Zero Touch Provisioning - Layer2 setup - Additional switches
  hosts: spine[0]
  become: true
  become_method: su
  become_user: root

  vars_files:
  - cli_vault.yml

  vars:
    spine_count: "{{ groups['spine'] | length }}"
    leaf_count: "{{ groups['new_leaf'] | length }}"

  tasks:
    # This task checks if valid number of spine and leaf switches are present in hosts file or not.
    # It will fail the playbook progress if only 1 spine is present or no leafs are present.
    - name: Check valid number of spine and leaf switches
      fail:
        msg: "Only 1 spine or no leaf switches present. Please check hosts file."
      when: "{{ spine_count }} <= 1 or {{ leaf_count }} == 0"

    # This task is to configure ZTP layer 2 setup for additional switches.
    # It uses pn_l2_ztp_additional_switches.py module from library/ directory.
    # pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
    # If the tasks fails then it will retry as specified by retries count.
    - name: Configure Auto vLags
      pn_l2_ztp_additional_switches:
        pn_cliusername: "{{ USERNAME }}"               # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"               # Cli password (value comes from cli_vault.yml).
        pn_spine_list: "{{ groups['spine'] }}"         # List of all spine switches mentioned under [spine] grp in hosts file.
        pn_new_leaf_list: "{{ groups['new_leaf'] }}"   # List of all leaf switches mentioned under [leaf] grp in hosts file.
        # pn_update_fabric_to_inband: False            # Flag to indicate if fabric network should be updated to in-band. Default: False.
        # pn_stp: False                                # Specify True if you want to enable STP at the end. Default: False.
      register: ztp_l2_out                      # Variable to hold/register output of the above tasks.
      until:  ztp_l2_out.failed != true         # If error pops up it will retry the code.
      retries: 3                                # This is the retries count.
      delay: 3
      ignore_errors: yes                        # Flag to indicate if we should ignore errors if any.

    - debug:
        var: ztp_l2_out                         # Print stdout_lines of register variable.

    - pause:
        seconds: 2                              # Pause playbook execution for specified amount of time.
