---

- name: Run local commands
  hosts: spine[0]
  serial: 1
  become: true
  become_method: su
  become_user: root

  vars_files:
  - cli_vault.yml

  vars:
  - csv_file: /etc/ansible/pluribus-ansible/ansible/cli_commands.csv

  tasks:
    - name: Run local commands
      pn_run_cli_commands:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_commands_file: "{{ lookup('file', '{{ csv_file }}') }}"
      register: commands_out
      until:  commands_out.failed != true  # if orror pops up it will retry the code
      retries: 3                       # ztp_out1.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 3
      ignore_errors: yes

    - debug:
        msg: "Commands ran successfully"

    - debug:
        var: commands_out.stdout_lines

    - pause:
        seconds: 2
 
