---


- name: Reset switches
  hosts: localhost

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Switch config reset
      pn_switch_config_reset:
        pn_cliusername: "{{ USERNAME }}"           # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"           # Cli password (value comes from cli_vault.yml).
        pn_host_list: "{{ groups['all'] }}"      # List of all leaf switches mentioned under [leaf] grp in hosts file.
        pn_host_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) | join(',') }}"
      register: reset_out                          # Variable to hold/register output of the above tasks.

    - name: Wait for nvOSd to reboot
      pause:
        minutes: 2
      when: reset_out.changed

