---


- name: Switch Config Reset
  hosts: all

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Reset all switches
      pn_switch_config_reset:
        pn_cliusername: "{{ USERNAME }}"  # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"  # Cli password (value comes from cli_vault.yml).
      register: reset_out                 # Variable to hold/register output of the above tasks.
      ignore_errors: yes

    - debug:
        var: reset_out.stdout_lines

    - pause:
        seconds: 10                       # Pause playbook execution for specified amount of time.
