---

- name: "ZTP Test"
  hosts: spine[1]
  user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Test Zero Touch Provisioning
      pn_test_ztp_l2:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_switch_count: '6'
