---

- name: "ZTP TEST"
  hosts: spine[1]
  become: true
  become_method: su
  become_user: root

  vars_files:
  - cli_vault.yml

  vars:
    spine_count: "{{ groups['spine'] | length }}"
    leaf_count: "{{ groups['leaf'] | length }}"

  tasks:
    - name: Test Layer3 Zero Touch Provisioning
      pn_test_ztp_l3:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_spine_count: "{{ spine_count }}"
        pn_leaf_count: "{{ leaf_count }}"
      register: ztp_out

    - debug:
        var: ztp_out.stdout_lines
