---

- name: "VFLOW CONFIGURATION"
  hosts: spine[0]
  user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Create vFlow
      pn_vflow:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: 'vflow-create'
        pn_name: 'drop_src_packets'
        pn_scope: 'local'
        pn_src_ip: '10.10.100.1'
        pn_action: 'drop'
