---


- name: Zero Touch Provisioning - Initial setup
  hosts: all
  serial: 1
  become: true
  user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Auto accept EULA, Disable STP, enable ports and create/join fabric
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        # pn_fabric_retry: 1
        pn_fabric_name: 'ztp-fabric'
        pn_run_l2_l3: False
      register: ztp_out
      until: ztp_out.failed != true  # if the above code fails it will retry the code
      retries: 3                     # ztp_out.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 3
      ignore_errors: yes

    - debug: var=ztp_out
    - pause: seconds=2


- name: Zero Touch Provisioning - Layer2 setup
  hosts: spine[0]
  serial: 1
  become: true
  become_user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Configure auto vlag
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_fabric_name: 'ztp-fabric'
        # pn_fabric_retry: 1
        pn_spine_list: "{{ groups['spine'] }}"
        pn_leaf_list: "{{ groups['leaf'] }}"
        pn_fabric_type: 'layer2'
        pn_run_l2_l3: True
      when: ztp_out.error != '1'         # if the above task fails then this task will not run
      register: ztp_l2_out
      until:  ztp_l2_out.failed != true  # if error pops up it will retry the code
      retries: 3                         # ztp_l2_out.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 3
      ignore_errors: yes

    - debug: var=ztp_l2_out
    - pause: seconds=2


- name: Virtual Router Redundancy Protocol (VRRP) - Layer 2 Setup
  hosts: spine[0]
  serial: 1
  become: true
  become_user: root

  vars_files:
  - cli_vault.yml

  vars:
  - csv_file: /etc/ansible/pluribus-ansible/ansible/pn_vrrp_l2.csv

  tasks:
    - name: VRRP L2 setup
      pn_ztp_vrrp_l2_csv:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_fabric_name: 'ztp-fabric'
        # pn_fabric_retry: 1
        pn_spine_list: "{{ groups['spine'] }}"
        pn_leaf_list: "{{ groups['leaf'] }}"
        pn_vrrp_id: '18'
        pn_vrrp_ip: '101.101.$.0/24'
        pn_active_switch: 'auto-spine2'
        pn_vlan_range: '100-200'
        pn_vrrp_no_interface: '100'
      register: vrrp_out
      until:  vrrp_out.failed != true  # if error pops up it will retry the code
      retries: 3                       # vrrp_out.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 3
      ignore_errors: yes

    - debug: var=vrrp_out
    - pause: seconds=2
