---
########## vRouter ##########


- name: "Create vRouter"
  hosts: testswitches[0]
  user: root
  gather_facts: True
  tags: charmander

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: spine1vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.1
        pn_bgp_as: 65000
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: spine1_vrouter
    - debug: var=spine1_vrouter
    - pause: seconds=2


- name: "Create vRouter"
  hosts: testswitches[1]
  user: root
  gather_facts: True
  tags: squirtle

  vars_files:
  - cli_vault.yml

  tasks: 


    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: spine2vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.2
        pn_bgp_as: 65000
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: spine2_vrouter
    - debug: var=spine2_vrouter
    - pause: seconds=2


- name: "Create vRouter"
  hosts: testswitches[2]
  user: pluribus
  gather_facts: True
  tags: pikachu

  vars_files:
  - cli_vault.yml

  tasks: 


    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: leaf1vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.3
        pn_bgp_as: 65001
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: leaf1_vrouter
    - debug: var=leaf1_vrouter
    - pause: seconds=2



- name: " Create vRouter"
  hosts: testswitches[3]
  user: pluribus
  gather_facts: True
  tags: gyarados

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: leaf2vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.4
        pn_bgp_as: 65002
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: leaf2_vrouter
    - debug: var=leaf2_vrouter
    - pause: seconds=2



- name: "Create vRouter"
  hosts: testswitches[4]
  user: pluribus
  gather_facts: True
  tags: lapras

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: leaf3vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.5
        pn_bgp_as: 65003
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: leaf3_vrouter
    - debug: var=leaf3_vrouter
    - pause: seconds=2


- name: "Create vRouter"
  hosts: testswitches[5]
  user: pluribus
  gather_facts: True
  tags: jigglypuff

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Create vRouter
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: vrouter-create
        pn_name: leaf4vrouter
        pn_vnet: no-fail-fab-global
        pn_router_type: hardware
        pn_router_id: 172.16.1.6
        pn_bgp_as: 65004
        pn_bgp_redistribute: connected
        pn_bgp_max_paths: 16
      register: leaf4_vrouter
    - debug: var=leaf4_vrouter
    - pause: seconds=2



########## Loopback interface ##########
- name: Gathering system facts
  hosts: testswitches[0:1]
  user: root
  gather_facts: True


- name: Gathering system facts
  hosts: testswitches[2:5]
  user: pluribus
  gather_facts: True


- name: "Add Loopback interface"
  hosts: testswitches[0]
  user: root
  tags: loopback

  vars_files:
  - cli_vault.yml

  tasks:

    - name: Add vRouter loopback interface
      pn_vrouterlbif:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-loopback-interface-add
        pn_vrouter_name: "{{ item.name }}"
        pn_interface_ip: "{{ item.ip }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter', ip: '172.16.1.1'}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.16.1.2'}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.16.1.3'}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.16.1.4'}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.16.1.5'}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.16.1.6'}
      register: loopback
    - debug: var=loopback
    - pause: seconds=2

########## L3 ports ##########
- name: Gathering system facts
  hosts: testswitches[0:1]
  user: root
  gather_facts: True


- name: Gathering system facts
  hosts: testswitches[2:5]
  user: pluribus
  gather_facts: True


- name: "Add L3"
  hosts: testswitches[0]
  user: root
  tags: layer3

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Add vRouter interface L3
      pn_vrouterif:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-interface-add
        pn_vrouter_name: "{{ item.name }}"
        pn_interface_ip: "{{ item.ip }}"
        pn_l3port: "{{ item.port }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.5/30', port: 41}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.1/30', port: 43}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.17/30', port: 45}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.21/30', port: 47}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.33/30', port: 39}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.37/30', port: 43}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.53/30', port: 45}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.49/30', port: 47}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.6/30', port: 1}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.34/30', port: 3}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.2/30', port: 1}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.38/30', port: 3}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.18/30', port: 1}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.54/30', port: 3}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.22/30', port: 1}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.50/30', port: 3}
      register: l3
    - debug: var=l3
    - pause: seconds=2



##########  BGP interfaces ##########
- name: Gathering system facts
  hosts: testswitches[0:1]
  user: root
  gather_facts: True


- name: Gathering system facts
  hosts: testswitches[2:5]
  user: pluribus
  gather_facts: True


- name: "Add BGP interfaces"
  hosts: testswitches[0]
  user: root
  tags: bgp

  vars_files:
  - cli_vault.yml

  tasks: 


    - name: Add vRouter BGP 
      pn_vrouterbgp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-bgp-add
        pn_vrouter_name: "{{ item.name }}"
        pn_neighbor: "{{ item.ip }}"
        pn_remote_as: "{{ item.remote }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.6', remote: 65001}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.2', remote: 65002}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.18', remote: 65003}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.22', remote: 65004}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.34', remote: 65001}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.38', remote: 65002}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.54', remote: 65003}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.50', remote: 65004}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.5', remote: 65000}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.33', remote: 65000}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.1', remote: 65000}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.37', remote: 65000}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.17', remote: 65000}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.53', remote: 65000}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.21', remote: 65000}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.49', remote: 65000}
      register: bgp
    - debug: var=bgp
    - pause: seconds=2



########## vLANs ##########
- name: Gathering system facts
  hosts: testswitches[0:1]
  user: root
  gather_facts: True


- name: Gathering system facts
  hosts: testswitches[2:5]
  user: pluribus
  gather_facts: True


- name: "Create vLANs"
  hosts: testswitches[0]
  user: root
  tags: vlan

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Create VLAN
      pn_vlan: pn_cliusername="{{ USERNAME }}" pn_clipassword="{{ PASSWORD }}" pn_cliswitch={{ item.switch }} pn_command=vlan-create pn_vlanid={{ item.id }} pn_scope=local
      with_items:
        - {switch: 'pikachu', id: 101}
        - {switch: 'gyarados', id: 102}
        - {switch: 'lapras', id: 103}
        - {switch: 'jigglypuff', id: 104}
      register: vlan
    - debug: var=vlan
    - pause: seconds=2


########## vRouter interface ##########
- name: Gathering system facts
  hosts: testswitches[0:1]
  user: root
  gather_facts: True


- name: Gathering system facts
  hosts: testswitches[2:5]
  user: pluribus
  gather_facts: True


- name: "Add interfaces"
  hosts: testswitches[0]
  user: root
  tags: interface

  vars_files:
  - cli_vault.yml

  tasks: 

    - name: Add vRouter interface 
      pn_vrouterif:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-interface-add
        pn_vrouter_name: "{{ item.name }}"
        pn_interface_ip: "{{ item.ip }}"
        pn_vlan: "{{ item.vlan }}"
      with_items:
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '101.101.101.2/24', vlan: 101}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '102.102.102.2/24', vlan: 102}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '103.103.103.2/24', vlan: 103}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '104.104.104.2/24', vlan: 104}
      register: interface
    - debug: var=interface
    - pause: seconds=2

