---
########## Delete vRouters and Interfaces ##########

- name: Delete vRouters and interfaces
  hosts: testswitches[0]
  user: root
  tags: router

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Remove vRouters and interfaces
      pn_vrouter:
        pn_cliusername: "{{ USERNAME }}" 
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-delete
        pn_name: "{{ item.name }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter'}
        - {switch: 'squirtle', name: 'spine2vrouter'}
        - {switch: 'pikachu', name: 'leaf1vrouter'}
        - {switch: 'gyarados', name: 'leaf2vrouter'}
        - {switch: 'lapras', name: 'leaf3vrouter'}
        - {switch: 'jigglypuff', name: 'leaf4vrouter'}
      register: router
    - debug: var=router


########## Delete vLANs ##########

- name: Delete vLANs
  hosts: testswitches[0]
  user: root
  tags: vlans
  
  vars_files:
  - cli_vault.yml

  tasks:
    - name: Delete vLANs
      pn_vlan: 
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vlan-delete
        pn_vlanid: "{{ item.id }}"
      with_items:
        - {switch: 'pikachu', id: 101}
        - {switch: 'gyarados', id: 102}
        - {switch: 'lapras', id: 103}
        - {switch: 'jigglypuff', id: 104}
      register: vlans
    - debug: var=vlans
