---
- name: "Teardown Fabric configurations..."
  hosts: testswitches[0]
  user: root
  tags: teardown

  vars_files:
  - cli_vault.yml

  tasks:

    - name: "Delete vRouter and interfaces"
      pn_vrouter: pn_cliusername={{ USERNAME }} pn_clipassword={{ PASSWORD }} pn_command=vrouter-delete pn_name={{ item }} 
      with_items: 
        - spine1vrouter
        - spine2vrouter
      register: vrouter_delete
    - debug: var=vrouter_delete

    
    - name: "Delete VLANs..."
      pn_vlan: pn_cliusername={{ USERNAME }} pn_clipassword={{ PASSWORD }} pn_command=vlan-delete pn_vlanid={{ item }}
      with_sequence: start=100 end=105
      register: vlan_delete
    - debug: var=vlan_delete
  
    
    - name: "Delete VLAGs..."
      pn_vlag: pn_cliusername={{ USERNAME }} pn_clipassword={{ PASSWORD }} pn_cliswitch={{ item.switch }} pn_command=vlag-delete pn_name={{ item.name }}
      with_items:
        - {switch: 'local', name: 'spine-to-leaf' }
        - {switch: 'local', name: 'spine-to-leaf3'}
        - {switch: 'local', name: 'spine-to-leaf4'}
        - {switch: 'pikachu', name: 'leafcluster-to-spinecluster'}
      register: vlag_delete
    - debug: var=vlag_delete


    - name: "Delete Trunks..."
      pn_trunk: pn_cliusername={{ USERNAME }} pn_clipassword={{ PASSWORD }} pn_cliswitch={{ item.switch }} pn_command=trunk-delete pn_name={{ item.name }} 
      with_items:
        - {switch: 'local', name: 'spine1-to-leaf'}
        - {switch: 'local', name: 'spine1-to-leaf3'}
        - {switch: 'local', name: 'spine1-to-leaf4'}
        - {switch: 'squirtle', name: 'spine2-to-leaf'} 
        - {switch: 'squirtle', name: 'spine2-to-leaf3'} 
        - {switch: 'squirtle', name: 'spine2-to-leaf4'}
        - {switch: 'pikachu', name: 'leaf1-to-spine'}
        - {switch: 'gyarados', name: 'leaf2-to-spine'}
      register: trunk_delete
    - debug: var=trunk_delete


    - name: "Delete Clusters..."
      pn_cluster: pn_cliusername={{ USERNAME }} pn_clipassword={{ PASSWORD }} pn_cliswitch={{ item.switch }} pn_command=cluster-delete pn_name={{ item.name }}
      with_items:
        - {switch: 'local', name: 'spinecluster'}
        - {switch: 'pikachu', name: 'leafcluster'}
      register: cluster_delete
    - debug: var=cluster_delete
