# This Playbook performs the following operations:
# 
# 1. Configure vRouter:
#     Tags: "bringup"
#     a. Create vLAN
#     b. Create vRouter
#     c. Add vRouter interface
#     d. Add VRRP interface
#     e. Add L3
#     f. Add vRouter loopback interface 
#     g. Add vRouter BGP
#     h. Add vRouter OSPF
#
# Modules used:
# 1. pn_vlan
# 2. pn_vrouter
# 3. pn_vrouterif
# 4. pn_vrouterbgp
# 5. pn_ospf
#

---

- name: "Configure vRouter..."
  hosts: testswitches[0]
  user: root
  tags: bringup

  tasks:

    - name: "Create a VLAN..."
      pn_vlan: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-create pn_vlanid=100 pn_scope=fabric
      register: vlan
    - debug: var=vlan


    - name: "Create vRouter... "
      pn_vrouter: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-create pn_name=spine1vrouter pn_vnet=puppet-ansible-fab-global pn_service_state=enable pn_hw_vrrp_id=18 pn_router_id=100.100.100.1 pn_bgp_as=25000
      register: vrouter
    - debug: var=vrouter


    - name: "Add vRouter interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip=101.101.101.2/24 pn_vlan=100 pn_interface=data
      register: interface
    - debug: var=interface


    - name: "Add VRRP interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_cliusername=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip=101.101.101.2/24 pn_vlan=100 pn_vrrp_id=18 pn_vrrp_ip=101.101.101.1/24 pn_interface=data pn_vrrp_priority=100 
      register: vrrp 
    - debug: var=vrrp


    - name: "Add L3 interface"
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip=172.16.1.1/24 pn_l3port=7
      register: l3iface
    - debug: var=l3iface


    - name: "Add vRouter loopback interface..."
      pn_vrouterlbif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-loopback-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip=192.168.11.12 pn_index=20
      register: loopback
    - debug: var=loopback


    - name: "Add vRouter BGP interface..."
      pn_vrouterbgp: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-bgp-add pn_vrouter_name=spine1vrouter pn_neighbor=102.102.102.1 pn_remote_as=25000
      register: bgp 
    - debug: var=bgp


    - name: "Add vRouter OSPF interface..."
      pn_ospf: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-ospf-add pn_vrouter_name=spine1vrouter pn_network_ip=172.26.1.0 pn_netmask=255.255.255.0 pn_ospf_area=0
      register: ospf 
    - debug: var=ospf
