# This Playbook performs the following operations:
#
# 1. Teardown vRouter configuration:
#     Tags: "teardown"
#     a. Remove vRouter OSPF
#     b. Remove vRouter BGP
#     c. Remove vRouter loopback interface
#     d. Remove VRRP interface
#     e. Remove L3
#     f. Remove vRouter interface
#     g. Delete vRouter (tags: router)
#     h. Delete vLAN (tags: vlan)
#
# Modules used:
# 1. pn_vlan
# 2. pn_vrouter
# 3. pn_vrouterif
# 4. pn_vrouterbgp
# 5. pn_ospf
#
---

- name: "Tear down vRouter configurations..."
  hosts: testswitches[0]
  user: root
  tags: teardown

  tasks:

    - name: "Remove vRouter OSPF interface..."
      pn_ospf: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-ospf-remove pn_vrouter_name=spine1vrouter pn_network_ip=172.26.1.0
      register: ospf_remove
    - debug: var=ospf_remove


    - name: "Remove vRouter BGP interface..."
      pn_vrouterbgp: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-bgp-remove pn_vrouter_name=spine1vrouter pn_neighbor=102.102.102.1
      register: bgp_remove
    - debug: var=bgp_remove


    - name: "Remove vRouter loopback interface..."
      pn_vrouterlbif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-loopback-interface-remove pn_vrouter_name=spine1vrouter pn_index=20
      register: loopback_remove
    - debug: var=loopback_remove


    - name: "Remove L3 interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-remove pn_vrouter_name=spine1vrouter pn_nic_str=<nic>
      register: l3iface_remove
    - debug: var=l3iface_remove

    
    - name: "Remove VRRP interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-remove pn_vrouter_name=spine1vrouter pn_nic_str=<nic>
      register: vrrp_remove
    - debug: var=vrrp_remove


    - name: "Remove vRouter interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-remove pn_vrouter_name=spine1vrouter pn_nic_str=<nic>
      register: interface_remove
    - debug: var=interface_remove


    - name: "Delete vRouter..."
      pn_vrouter: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-delete pn_name=spine1vrouter
      register: vrouter_delete
      tags: router
    - debug: var=vrouter_delete


    - name: "Delete VLAN..."
      pn_vlan: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-delete pn_vlanid=100
      register: vlan_delete
    - debug: var=vlan_delete
