---

######## ZTP ##########

- name: "Zero Touch Provisioning - Initial setup"
  hosts: spine[0]
  serial: 1
  user: root
  
  vars_files:
  - cli_vault.yml

  tasks:

    - name: BGP MODULE
      pn_ztp2:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        #pn_fabric_retry: 1
        pn_fabric_name: ztp-fabric
        pn_run_l2_l3: False
        pn_spine_list: "{{ groups['spine'] }}"
        pn_leaf_list: "{{ groups['leaf'] }}"
        #pn_bgp_maxpath:                                               #default 16
        #pn_bgp_redistribute:                                          #default connected
        #pn_bgp_as_range:                                              #default 65000
      register: ztp_out
      until: ztp_out.failed != true              # if the above code fails it will retry the code
      retries: 3                                # ztp_out.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 1
      ignore_errors: yes      
       
    - debug: var=ztp_out
    - pause: seconds=2

