---

- name: "Zero Touch Provisioning - Layer2 setup"
  hosts: spine[0]
  serial: 1
  user: root

  vars_files:
  - cli_vault.yml

  tasks:

    - name: Auto vlag 
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_fabric_name: ztp-fabric
        # pn_fabric_retry: 1
        pn_spine_list: "{{ groups['spine'] }}"
        pn_leaf_list: "{{ groups['leaf'] }}"
        pn_fabric_type: layer2
        pn_run_l2_l3: True
        pn_net_address: '172.168.0.0'
        pn_cidr: '24'
        pn_supernet: '30'
        pn_vrrp_id: '18'
        pn_vrrp_ip: '101.101.$.0/24'
        pn_active_switch: 'auto-spine2'
        pn_vlan_range: '101-200'
        pn_vrrp_no_interface: '4'

      register: ztp_out1
      until:  ztp_out1.failed != true                    # if orror pops up it will retry the code
      retries: 3                                       # ztp_out1.retry can be used in place of 3 if the value is given as pn_fabric_retry
      delay: 1
      ignore_errors: yes
    - debug: var=ztp_out1
    - pause: seconds=2


