---

- name: "VFLOW CONFIGURATION"
  hosts: spine[0]
  user: root

  vars_files:
  - cli_vault.yml

  tasks:
    - name: Delete vFlow
      pn_vflow:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_command: 'vflow-delete'
        pn_name: 'drop_src_packets'
