########## BGP remove ##########
---
- name: Remove BGP neighbors from vRouters
  hosts: testswitches[0]
  user: root
  tags: bgp

  tasks:
    - name: Remove BGP
      pn_vrouterbgp:
        pn_cliusername: network-admin
        pn_clipassword: test123
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-bgp-remove
        pn_vrouter_name: "{{ item.name }}"
        pn_neighbor: "{{ item.ip }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.6'}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.2'}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.18'}
        - {switch: 'local', name: 'spine1vrouter', ip: '172.168.10.22'}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.34'}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.38'}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.54'}
        - {switch: 'squirtle', name: 'spine2vrouter', ip: '172.168.10.50'}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.5'}
        - {switch: 'pikachu', name: 'leaf1vrouter', ip: '172.168.10.33'}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.1'}
        - {switch: 'gyarados', name: 'leaf2vrouter', ip: '172.168.10.37'}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.17'}
        - {switch: 'lapras', name: 'leaf3vrouter', ip: '172.168.10.53'}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.21'}
        - {switch: 'jigglypuff', name: 'leaf4vrouter', ip: '172.168.10.49'}
      register: bgp
    - debug: var=bgp



########## Delete vRouters and Interfaces ##########

- name: Delete vRouters and interfaces
  hosts: testswitches[0]
  user: root
  tags: router

  tasks:
    - name: Remove vRouters and interfaces
      pn_vrouter:
        pn_cliusername: network-admin
        pn_clipassword: test123
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vrouter-delete
        pn_name: "{{ item.name }}"
      with_items:
        - {switch: 'local', name: 'spine1vrouter'}
        - {switch: 'squirtle', name: 'spine2vrouter'}
        - {switch: 'pikachu', name: 'leaf1vrouter'}
        - {switch: 'gyarados', name: 'leaf2vrouter'}
        - {switch: 'lapras', name: 'leaf3vrouter'}
        - {switch: 'jigglypuff', name: 'leaf4vrouter'}
      register: router
    - debug: var=router


########## Delete vLANs ##########

- name: Delete vLANs
  hosts: testswitches[0]
  user: root
  tags: vlans
  
  tasks:
    - name: Delete vLANs
      pn_vlan: 
        pn_cliusername: network-admin
        pn_clipassword: test123
        pn_cliswitch: "{{ item.switch }}"
        pn_command: vlan-delete
        pn_vlanid: "{{ item.id }}"
      with_items:
        - {switch: 'pikachu', id: 101}
        - {switch: 'gyarados', id: 102}
        - {switch: 'lapras', id: 103}
        - {switch: 'jigglypuff', id: 104}
      register: vlans
    - debug: var=vlans


