---
- name: Test vlan create
  user: root
  hosts: testswitches[2]

  vars_files:
  - vault-vars.yml
  
  tasks:
  - name: Test vlan-create without password
    pn_vlan: pn_command=vlan-create pn_vlanid=300 pn_scope=fabric
    register: output1
  - debug: var=output1

#- name: Test vlan-create
#  user: pluribus
#  hosts: testswitches[2]

#  tasks:
  - name: Test vlan-create with password
    pn_vlan: 
      pn_cliusername={{ USER }}
      pn_clipassword={{ PASSWORD }}
      pn_command=vlan-create 
      pn_vlanid=302 
      pn_scope=fabric
    register: output2
    no_log: True
  - debug: var=output2
    no_log: True
