# This Playbook creates vRouter configurations on spine switches.
# spine1vrouter on charmander(spine1) and spine2vrouter on squirtle(spine2)
# Creates VLANs and vRouters.
# Adds IP interfaces, VRRP interfaces, and L3 port. 

---
- name: "Configure vRouter..."
  hosts: charmander
  user: root

  tasks:

    - name: "Create VLANs..."
      pn_vlan: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vlan-create pn_vlanid={{ item }} pn_scope=fabric
      with_sequence: start=201 end=205
      register: result
    - debug: var=result

    - name: "Create vRouter... "
      pn_vrouter: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-create pn_name=spine1vrouter pn_vnet=puppet-ansible-fab-global pn_service_state=enable pn_hw_vrrp_id=18 pn_bgp_as=30000
      register: vrouter 
    - debug: var=vrouter 


    - name: "Add vRouter interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip={{ item.ip }} pn_vlan={{ item.vlan }} pn_interface=data
      with_items:
        - {ip: '201.201.201.2/24', vlan: 201}
        - {ip: '202.202.202.2/24', vlan: 202}
        - {ip: '203.203.203.2/24', vlan: 203}
        - {ip: '204.204.204.2/24', vlan: 204}
        - {ip: '205.205.205.2/24', vlan: 205}
      register: interface 
    - debug: var=interface


    - name: "Add VRRP interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip={{ item.ip }} pn_vrrp_ip={{ item.vrrp }} pn_vrrp_priority={{ item.priority }} pn_vrrp_id=18 pn_vlan={{ item.vlan }} pn_interface=data
      with_items:
        - {ip: '201.201.201.2/24', vrrp: '201.201.201.1/24', priority: '210', vlan: 201}
        - {ip: '202.202.202.2/24', vrrp: '202.202.202.1/24', priority: '210', vlan: 202}
        - {ip: '203.203.203.2/24', vrrp: '203.203.203.1/24', priority: '210', vlan: 203}
        - {ip: '204.204.204.2/24', vrrp: '204.204.204.1/24', priority: '200', vlan: 204}
        - {ip: '205.205.205.2/24', vrrp: '205.205.205.1/24', priority: '200', vlan: 205}
      register: vrrp 
    - debug: var=vrrp


    - name: "Add L3 port..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine1vrouter pn_interface_ip=172.16.1.1/24 pn_l3port=7
      register: l3iface
    - debug: var=l3iface



- name: "Configure vRouter..."
  hosts: squirtle
  user: root

  tasks:

    - name: "Create vRouter... "
      pn_vrouter: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-create pn_name=spine2vrouter pn_vnet=puppet-ansible-fab-global pn_service_state=enable pn_hw_vrrp_id=18 pn_bgp_as=30000
      register: vrouter 
    - debug: var=vrouter 


    - name: "Add vRouter interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine2vrouter pn_interface_ip={{ item.ip }} pn_vlan={{ item.vlan }} pn_interface=data
      with_items:
        - {ip: '201.201.201.3/24', vlan: 201}
        - {ip: '202.202.202.3/24', vlan: 202}
        - {ip: '203.203.203.3/24', vlan: 203}
        - {ip: '204.204.204.3/24', vlan: 204}
        - {ip: '205.205.205.3/24', vlan: 205}
      register: interface 
    - debug: var=interface


    - name: "Add VRRP interface..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine2vrouter pn_interface_ip={{ item.ip }} pn_vrrp_ip={{ item.vrrp }} pn_vrrp_priority={{ item.priority }} pn_vrrp_id=18 pn_vlan={{ item.vlan }} pn_interface=data
      with_items:
        - {ip: '201.201.201.3/24', vrrp: '201.201.201.1/24', priority: '210', vlan: 201}
        - {ip: '202.202.202.3/24', vrrp: '202.202.202.1/24', priority: '210', vlan: 202}
        - {ip: '203.203.203.3/24', vrrp: '203.203.203.1/24', priority: '210', vlan: 203}
        - {ip: '204.204.204.3/24', vrrp: '204.204.204.1/24', priority: '200', vlan: 204}
        - {ip: '205.205.205.3/24', vrrp: '205.205.205.1/24', priority: '200', vlan: 205}
      register: vrrp 
    - debug: var=vrrp


    - name: "Add L3 port..."
      pn_vrouterif: pn_cliusername=network-admin pn_clipassword=test123 pn_command=vrouter-interface-add pn_vrouter_name=spine2vrouter pn_interface_ip=172.16.1.1/24 pn_l3port=8
      register: l3iface
    - debug: var=l3iface
