---

########## ZTP ##########


- name: "Zero Touch Provisioning - Initial setup"
  hosts: all
  user: root

  vars_files:
  - cli_vault.yml

  tasks:

    - name: Auto accept EULA, Disable STP, enable ports and create/join fabric
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_fabric_name: ztp-fabric
        pn_run_l2_l3: False
      register: ztp_out
    - debug: var=ztp_out
    - pause: seconds=2

- name: "Zero Touch Provisioning - Layer2/Layer3 setup"
  hosts: spine[0]
  user: root

  vars_files:
  - cli_vault.yml

  tasks:

    - name: Auto vlag or Auto configure link IPs
      pn_ztp:
        pn_cliusername: "{{ USERNAME }}"
        pn_clipassword: "{{ PASSWORD }}"
        pn_fabric_name: ztp-fabric
        pn_fabric_type: layer3
        pn_run_l2_l3: True
        pn_net_address: '192.168.0.1'
        pn_cidr: '24'
        pn_supernet: '30'
      register: ztp_out
    - debug: var=ztp_out
    - pause: seconds=2
