#L2 ZTP
---


# This task is to configure ZTP layer 2 setup.
# It uses pn_l2_ztp.py module from library/ directory.
# pn_cliusername and pn_clipassword comes from vars file - cli_vault.yml
# If the tasks fails then it will retry as specified by retries count.
- name: Zero Touch Provisioning - Layer2 setup
  hosts: spine[0]
  become: true
  become_method: su
  become_user: root

  vars_files:
  - ../playbookvariables/cli_vault.yml
  - ../playbookvariables/vars_l2_ztp.yml

  tasks:
    - name: Configure auto vlag
      pn_l2_ztp:
        pn_cliusername: "{{ USERNAME }}"        # Cli username (value comes from cli_vault.yml).
        pn_clipassword: "{{ PASSWORD }}"        # Cli password (value comes from cli_vault.yml).
        pn_spine_list: "{{ groups['spine'] }}"  # List of all spine switches mentioned under [spine] grp in hosts file.
        pn_leaf_list: "{{ groups['leaf'] }}"    # List of all leaf switches mentioned under [leaf] grp in hosts file.
        pn_update_fabric_to_inband: "{{ pn_update_fabric_to_inband }}"  # Flag to indicate if fabric network should be updated to in-band. Default: False.
        pn_stp: "{{ pn_stp }}"                  # Specify True if you want to enable STP at the end. Default: False.

      register: ztp_l2_out                      # Variable to hold/register output of the above tasks.
      until:  ztp_l2_out.failed != true         # If error pops up it will retry the code.
      retries: 3                                # This is the retries count.
      delay: 3
      ignore_errors: yes                        # Flag to indicate if we should ignore errors if any.

    - debug:
        var: ztp_l2_out.stdout_lines            # Print stdout_lines of register variable.

    - pause:
        seconds: 2                              # Pause playbook execution for specified amount of time.
