---
# This playbook is to setup SSH keys between localhost and remote switches.
# It uses the pn_autossh module.
# The list of switch IP addresses is passed as a csv file.
# The variables are located in vars_sshkeys.yml file.

- name: Auto SSH setup
  hosts: localhost

  vars_files:
    - ../playbookvariables/cli_vault.yml
    - ../playbookvariables/vars_sshkeys.yml

  tasks:
    - name: Generate SSH keys and push them onto switches
      pn_autossh:
        pn_user: "{{ remote_user }}"
        pn_ssh_password: "{{ PASSWORD }}"
        pn_hosts_csv:  "{{ lookup('file', '{{ csv_file }}') }}" #['10.9.21.60', '10.9.21.61', '10.9.21.62', '10.9.21.63', '10.9.21.64', '10.9.21.65']
        pn_overwrite: False
        pn_filepath: "{{ lookup('env','HOME') + '/.ssh/id_rsa' }}"
      register: output
      
    - debug: var=output.stdout_lines
