---
#L2 VRRP

pn_update_fabric_to_inband: False     # optional, True:False, Flag to update fabric network to in-band, Update Fabric Network, text
pn_stp: True                          # optional, True:False, Flag to enable STP at the end of configuration, STP, boolean
csv_file: vrrp_l2.csv                 # mandatory, , Layer2 VRRP data csv file, CSV File, file 
pn_vrrp_id: '18'                      # optional, 18, Specify VRRP ID to be assigned, VRRP ID, text
