---
- name: PN-CLI trunk Delete
  hosts: newswitches
  user: pluribus
  

  tasks:
  - name: Delete trunk 
    pn_trunk: pn_cliusername=network-admin pn_clipassword=test123 pn_trunkcommand=trunk-delete pn_trunkname=ansible-trunk pn_quiet=True
    register: cmd_output
  - debug: var=cmd_output 
