---
- name: PN-CLI VLAG Create
  hosts: testswitches
  user: root
  

  tasks:
  - name: Create VLAG 
    pn_vlag: pn_vlagcommand='vlag-create' pn_vlagname='ansible-vlag3' pn_vlaglport=52 pn_vlagpeerport=71 pn_vlagmode='active-active' pn_quiet=True
    register: cmd_output
  - debug: var=cmd_output 
